### ISSUE TITLE
1.1.0 版本的npm包不见了呢

### ISSUE THREAD

**Issue by helianthuswhite** [react-component/portal#13]
使用antd v5的项目 install 时报错 404，发现是 `@rc-component/portal` 这个包找不到了，直接打开链接 https://registry.npmjs.org/@rc-component/portal/-/portal-1.1.0.tgz 发现会报 `Not found` 的错误。在npm上搜索 `@rc-component/portal` 包打开也会报错 `Service Unavailable`。

**Comment by KyMback** [comment]
the same

**Comment by parthjmistry** [comment]
+1

**Comment by iamchrisdev** [comment]
+1

**Comment by helianthuswhite** [comment]
目前好像恢复了。
It seems to be ok now.

**Comment by afc163** [comment]
https://status.npmjs.org/ npm 有故障。
