### ISSUE TITLE
rc-util not high enough version

### ISSUE THREAD

**Issue by sdb1228** [react-component/portal#6]
This project is used within the antd repo (specifically the antd drawer and dialog). In here inside the https://github.com/react-component/portal/blob/master/src/useScrollLocker.tsx file you reference the removeCSS call from dynamicCSS inside rc-util.  That function wasn't introduced till a later version.  Can we get that package bumped and consumed within antd or is there a workaround that can help? I can also put up a PR if that is easier for to grasp.

Thanks!

**Comment by Veveue** [comment]
```

This dependency was not found:

* rc-util/es/hooks/useLayoutEffect in ./node_modules/@rc-component/portal/es/useDom.js, ./node_modules/@rc-component/portal/es/useScrollLocker.js

```

@afc163
